version: '3'
services:
  nginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - "./nginx/conf.d/:/etc/nginx/conf.d/"
      - "./nginx/rails/:/usr/share/nginx/rails/"
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
